
airfoil:
  contour_file: "ONERA-OAT15A_coordiantes.dat"   

  spline_degree: 2                                

airfoil_boundary:                                  
  n_points: 500
  n_points_te: 10
  weight_upper: 1.0
  weight_curvature: 4.0
  weight_te: 4.0
  fraction_te: 0.2
  max_size_ratio: 1.15
  n_points_high_res: 5000
  max_relax_iter: 100

airfoil_extrusion:                                 
  cell_thickness: 0.00001
  growth: 1.03
  extrusion_distance: 0.3

shock_box:
  growth: 1.01
  box_height: 0.6
  xmin: 0.05
  xmax: 0.7

wake_tunnel:
  n_points: 70
  make_curve: True
  fraction_structured: 0.5 #(if make_curve == True)
  length: 5.0
  angle: 5.0

tria_mesh_settings:
  wake_size: 0.02
  farfield:
    min_size: 0.02
    max_size: 3.2
    grading: 0.01

farfield:
  radius: 50
  length: 100

output:
  obj_filename: "mesh.obj"